//Generated by HIM
#include "szakdoga.h"

hashtable* aliases_hashbtable(){
	hashtable* aliases = hashtable_init(256, sizeof(char[10]), sizeof(char[10]));

	//aliases for iso88592
	const char* encoding_iso88592 = "iso88592\0";
	hashtable_put(aliases,encoding_iso88592,encoding_iso88592);

	//put to iso88592 alias latin2
	const char* alias_latin2_for_iso88592 = "latin2\0\0\0";
	hashtable_put(aliases,alias_latin2_for_iso88592,encoding_iso88592);


	return aliases;
	}

hashtable* unit_lenghts(){
	hashtable* unit_lengths = hashtable_init(128, sizeof(char[10]), sizeof(uint8_t));

	//unit legnths for iso88592
	const char* encoding_iso88592 = "iso88592\0";
	uint8_t length_iso88592 = 1;
	hashtable_put(unit_lengths, encoding_iso88592, &length_iso88592);

	//unit length for ascii
	const char* encoding_iso88592_to_ascii = "ascii\0\0\0\0";
	uint8_t length_iso88592_to_ascii = 1;
	hashtable_put(unit_lengths, encoding_iso88592_to_ascii, &length_iso88592_to_ascii);


	return unit_lengths;
	}

hashtable* mappings(){
	// hashtable for everything
	hashtable* mappings = hashtable_init(128, sizeof(char[10]), sizeof(hashtable*));

	// hashtable for iso88592
	const char* encoding_iso88592 = "iso88592\0";
	hashtable* mappings_from_iso88592 = hashtable_init(128, sizeof(char[10]), sizeof(hashtable*));
	hashtable_put(mappings, encoding_iso88592, &mappings_from_iso88592);

	// hash for iso88592->ascii
	const char* encoding_iso88592_to_ascii = "ascii\0\0\0\0";
	hashtable* mappings_from_iso88592_to_ascii = hashtable_init(
		512,
		sizeof(uint8_t),
		sizeof(uint8_t));
	hashtable_put(mappings_from_iso88592, encoding_iso88592_to_ascii, &mappings_from_iso88592_to_ascii);

	//filling in iso88592->ascii
	uint8_t from_value_iso88592_to_ascii;
	uint8_t to_value_iso88592_to_ascii;

	from_value_iso88592_to_ascii = 225;
	to_value_iso88592_to_ascii = 97;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 233;
	to_value_iso88592_to_ascii = 101;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 237;
	to_value_iso88592_to_ascii = 105;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 243;
	to_value_iso88592_to_ascii = 111;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 246;
	to_value_iso88592_to_ascii = 111;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 245;
	to_value_iso88592_to_ascii = 111;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 250;
	to_value_iso88592_to_ascii = 117;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 252;
	to_value_iso88592_to_ascii = 117;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 251;
	to_value_iso88592_to_ascii = 117;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 228;
	to_value_iso88592_to_ascii = 97;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 193;
	to_value_iso88592_to_ascii = 65;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 201;
	to_value_iso88592_to_ascii = 69;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 205;
	to_value_iso88592_to_ascii = 73;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 211;
	to_value_iso88592_to_ascii = 79;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 214;
	to_value_iso88592_to_ascii = 79;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 213;
	to_value_iso88592_to_ascii = 79;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 218;
	to_value_iso88592_to_ascii = 85;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 220;
	to_value_iso88592_to_ascii = 85;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 219;
	to_value_iso88592_to_ascii = 85;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);

	from_value_iso88592_to_ascii = 196;
	to_value_iso88592_to_ascii = 65;
	hashtable_put(
		mappings_from_iso88592_to_ascii,
		&from_value_iso88592_to_ascii,
		&to_value_iso88592_to_ascii);



	return mappings;
}
