//Generated by HIM
#include "test3.h"

hashtable* aliases_hashbtable(){
	hashtable* aliases = hashtable_init(256, sizeof(char[10]), sizeof(char[10]));

	//aliases for ascii
	const char* encoding_ascii = "ascii\0\0\0\0";
	hashtable_put(aliases,encoding_ascii,encoding_ascii);

	//put to ascii alias Ascii
	const char* alias_Ascii_for_ascii = "Ascii\0\0\0\0";
	hashtable_put(aliases,alias_Ascii_for_ascii,encoding_ascii);


	//aliases for a
	const char* encoding_a = "a\0\0\0\0\0\0\0\0";
	hashtable_put(aliases,encoding_a,encoding_a);


	return aliases;
	}

hashtable* unit_lenghts(){
	hashtable* unit_lengths = hashtable_init(128, sizeof(char[10]), sizeof(uint8_t));

	//unit legnths for ascii
	const char* encoding_ascii = "ascii\0\0\0\0";
	uint8_t length_ascii = 1;
	hashtable_put(unit_lengths, encoding_ascii, &length_ascii);

	//unit length for UTF8
	const char* encoding_ascii_to_UTF8 = "UTF8\0\0\0\0\0";
	uint8_t length_ascii_to_UTF8 = 1;
	hashtable_put(unit_lengths, encoding_ascii_to_UTF8, &length_ascii_to_UTF8);


	//unit legnths for a
	const char* encoding_a = "a\0\0\0\0\0\0\0\0";
	uint8_t length_a = 1;
	hashtable_put(unit_lengths, encoding_a, &length_a);

	//unit length for b
	const char* encoding_a_to_b = "b\0\0\0\0\0\0\0\0";
	uint8_t length_a_to_b = 3;
	hashtable_put(unit_lengths, encoding_a_to_b, &length_a_to_b);


	return unit_lengths;
	}

hashtable* mappings(){
	// hashtable for everything
	hashtable* mappings = hashtable_init(128, sizeof(char[10]), sizeof(hashtable*));

	// hashtable for ascii
	const char* encoding_ascii = "ascii\0\0\0\0";
	hashtable* mappings_from_ascii = hashtable_init(128, sizeof(char[10]), sizeof(hashtable*));
	hashtable_put(mappings, encoding_ascii, &mappings_from_ascii);

	// hash for ascii->UTF8
	const char* encoding_ascii_to_UTF8 = "UTF8\0\0\0\0\0";
	hashtable* mappings_from_ascii_to_UTF8 = hashtable_init(
		512,
		sizeof(uint8_t),
		sizeof(uint8_t));
	hashtable_put(mappings_from_ascii, encoding_ascii_to_UTF8, &mappings_from_ascii_to_UTF8);

	//filling in ascii->UTF8
	uint8_t from_value_ascii_to_UTF8;
	uint8_t to_value_ascii_to_UTF8;

	from_value_ascii_to_UTF8 = 101;
	to_value_ascii_to_UTF8 = 69;
	hashtable_put(
		mappings_from_ascii_to_UTF8,
		&from_value_ascii_to_UTF8,
		&to_value_ascii_to_UTF8);

	from_value_ascii_to_UTF8 = 120;
	to_value_ascii_to_UTF8 = 48;
	hashtable_put(
		mappings_from_ascii_to_UTF8,
		&from_value_ascii_to_UTF8,
		&to_value_ascii_to_UTF8);



	// hashtable for a
	const char* encoding_a = "a\0\0\0\0\0\0\0\0";
	hashtable* mappings_from_a = hashtable_init(128, sizeof(char[10]), sizeof(hashtable*));
	hashtable_put(mappings, encoding_a, &mappings_from_a);

	// hash for a->b
	const char* encoding_a_to_b = "b\0\0\0\0\0\0\0\0";
	hashtable* mappings_from_a_to_b = hashtable_init(
		512,
		sizeof(uint8_t),
		sizeof(uint32_t));
	hashtable_put(mappings_from_a, encoding_a_to_b, &mappings_from_a_to_b);

	//filling in a->b
	uint8_t from_value_a_to_b;
	uint32_t to_value_a_to_b;

	from_value_a_to_b = 69;
	to_value_a_to_b = 4569632;
	hashtable_put(
		mappings_from_a_to_b,
		&from_value_a_to_b,
		&to_value_a_to_b);



	return mappings;
}
