//Generated by HIM
#ifndef TEST3_GEN_H
#define TEST3_GEN_H

#include <stdint.h>
#include <assert.h>
#include "hashtable.h"

hashtable* aliases_hashbtable();
hashtable* unit_lenghts();
hashtable* mappings();

#endif
